pkg/client/linstor.go, pkg/driver/driver.go, pkg/driver/driver_test.go
The key ideas here are:
- the linstorifyResourceName algorithm which generates valid LINSTOR names. I assume that eventually such functionality will land in LINSTOR itself. So for now do not push that to `golinstor`. I hope we can remove that code in the future.
- remove the prefix as it is not needed any more on this "global" level. but keep it in the driver itself.
- don't break existing resources.
Feedback is welcome. If OK, feel free to merge.
Regards, rck
=> CreateVolume: use suggested name if possible

examples/k8s/deploy/linstor-csi-1.16.yaml
Old apiVersions removed since kubernetes 1.16.0.
Example manifest is not working anymore.
=> Add example for kubernetes 1.16

examples/k8s/deploy/linstor-csi-1.17.yaml
This PR is doing:
- Deprecate Cluster Driver Registrar (more info [here](https://github.com/kubernetes-csi/cluster-driver-registrar#note))
- Update csi-images to latest versions
Tested on Kubernetes 1.17
fixes: https://github.com/LINBIT/linstor-csi/issues/45
fixes: https://github.com/LINBIT/linstor-csi/issues/36
=> Add example for kubernetes 1.17

examples/k8s/deploy/linstor-csi-1.16.yaml, examples/k8s/deploy/linstor-csi-1.17.yaml
Hi, linstor-csi plugin is working fine without host networking.
This parameter was given here by mistake, actually I'm not using hostNetwork in [kube-linstor](https://github.com/kvaps/kube-linstor/blob/master/helm/kube-linstor/templates/linstor-csi.yaml) project
=> Disable host network

examples/k8s/deploy/linstor-csi-1.17.yaml
There is also one breaking change about snapshots
https://github.com/kubernetes-csi/external-provisioner/blob/master/CHANGELOG-1.5.md
=> Update csi images to latest versions for 1.17

pkg/topology/scheduler/balancer/balancer.go
Linstor v1.4.2 introduced that DfltDisklessStorPool is not filtered which is breaking balancer scheduler. This is fix for that.
=> Do not use DfltDisklessStorPool in balancer scheduler

examples/k8s/deploy/linstor-csi-1.17.yaml
This PR drops permissions for read secrets in all cluster for linstor-csi-provisioner and linstor-csi-snapshoter.
This is not required for LINSTOR.
=> Drop secrets permission

pkg/volume/volume.go
For LINSTOR it is perfectly fine that a RG does not contain a dedicated
storage pool. LINSTOR then chooses one.
In this case the Go string for the SP if not set in the SC had it's
default value (i.e., ""). This was then set on the RG, which then is not
valid in later on in LINSTOR.
=> allow empty storage pools

CHANGELOG.md, pkg/client/linstor.go
CSI Node needs annotations on resource definitions to determine
which volume to mount. On snapshot restore, LINSTOR will overwrite
all props of a RD with the original value. This lead to CSI Node mounting
the "original" volume instead of the one restored from a snapshot.
The fix is to move the creation/update of these annotations to the end
of the snapshot-restore method.
=> ensure annotations on RDs are up-to-date

examples/k8s/class.yaml, examples/k8s/deploy/linstor-csi-1.17.yaml
Update manifests to support volume resizing
do not merge until preparing docker image with https://github.com/piraeusdatastore/linstor-csi/pull/70
=> Enable volume resizing

.github/workflows/build.yml
The default checkout action only fetches a single commit. For
git describe to work we need access to the history (until the latest tag)
We cannot know ahead of time how many commits we need to fetch, so instead
we fetch the entire history
Fix for #79
=> CI: fix git describe failure

pkg/volume/volume.go
This fixes a convenience issue that bit some users already. LINSTOR aux
properties need the "Aux/" prefix on their keys. With that in place
users can specify it in "LINSTOR notation" with the prefix, or leave it
out and then the driver adds them. The LINSTOR command line client also
automatically adds the prefix under certain conditions, so it should be
fine to add this magic here as well.
The prefix is added to "replicasOnSame" and "replicasOnDifferent".
This allows:
parameters:
autoPlace: "2"
replicasOnDifferent: Aux/zone
resourceGroup: linstor-volume-r2
as well as:
parameters:
autoPlace: "2"
replicasOnDifferent: zone
resourceGroup: linstor-volume-r2
=> add "Aux/" prefix to RG props

README.md, examples/k8s/deploy/linstor-csi-dev.yaml
The last dev deployment example was not updated to support newer
kubernetes versions. Newer kubernetes distributions removed support
for some of the API versions which were still in use. This commit
updates the dev deployment to be in line with the 1.17 deployment.
Also adds a clarification that this project only deploys the CSI
components and links to the operator for more information.
=> Update dev deployment to be up-to-date with 1.17

examples/k8s/deploy/linstor-csi-1.19.yaml
Similar changes are [committed](https://github.com/kvaps/kube-linstor/commit/261acdf0b970f8f874b8189d81104c97cc3a2f94) to Kube-Linstor v1.9.0
Changes since the previous version
```diff
--- linstor-csi-1.17.yaml	2020-08-07 16:08:50.108707407 +0200
+++ linstor-csi-1.19.yaml	2020-10-04 23:19:34.282299044 +0200
@@ -21,7 +21,7 @@
serviceAccount: linstor-csi-controller-sa
containers:
- name: csi-provisioner
-          image: quay.io/k8scsi/csi-provisioner:v1.5.0
+          image: quay.io/k8scsi/csi-provisioner:v2.0.2
args:
- "--csi-address=$(ADDRESS)"
- "--v=5"
@@ -35,7 +35,7 @@
- name: socket-dir
mountPath: /var/lib/csi/sockets/pluginproxy/
- name: csi-attacher
-          image: quay.io/k8scsi/csi-attacher:v2.1.1
+          image: quay.io/k8scsi/csi-attacher:v3.0.0
args:
- "--v=5"
- …
```
=> update example deployment for k8s 1.19

CHANGELOG.md, pkg/driver/driver.go
DRBD and by extension LINSTOR support ROX configurations, as
long as the device is mounted with the "ro" option. This commit enables
the CSI driver to provision such ROX volumes. For this to work we need to:
* tell CSI we can handle ROX configurations
* validate ROX volumes are used with the "readOnly" option set
=> Add support for ROX volumes

CHANGELOG.md, pkg/client/linstor.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/volume/volume.go
Block volumes are special, extra care must be taken such that they
are not accidentally opened RW in ROX mode. In our setup, block volumes
are exposed to Kubernetes as simple bind mounts (with "ro").
However, it is still possible to open DRBD devices as O_RDWR through the
bind mount. In a later stage, Kubernetes sets up a loop device using
losetup for our block volume. By default, losetup opens the device
as O_RDWR if it can. This means we need a way to disallow O_RDWR on
our exported devices.
The solution implemented here is to set up _another_ loop device, using
losetup's "--read-only" option to ensure the backing device is only opened
using O_RDONLY.
=> add support for ROX block volumes

examples/k8s/class.yaml
When using newer CSI components, no default fstype is set for PVs.
This leads to kubelet skipping the fsGroup step since it expects
the volume to be in block mode.
See https://github.com/piraeusdatastore/linstor-csi/issues/91
=> use explicit fstype in storageclass example

CHANGELOG.md, pkg/client/linstor.go
In d2f23d6 we introduced ROX volume support, which works around DRBD's
autopromote feature by introducing a readonly loop-device so all access
is done readonly.
The code to handle detaching needed to clean up the loop device, which
relied on a specifc implementation of "losetup --list", which is not
compatible with older version (such as the one found in CentOS 7).
This meant that _all_ PVC failed to detach.
This commit switches to using "blockdev --setro" to ensure readonly access.
That in turn requires DRBD v9.0.26, which is not released yet. This should
not be a problem, as the feature was probably never used anyways.
=> remove losetup dependency for ROX support

CHANGELOG.md, pkg/client/linstor.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/volume/volume.go
This commit adds a missing check to NodePublishVolume that ensures the
volume exists in the LINSTOR backend.
The method "GetByID" was renamed to "FindByID". This should help indicate
that a "nil, nil" return is possible. For the same reason, "GetByName"
was renamed "FindByName".
Fixes #96
=> fix: NodePublishVolume checks for nil volumes

CHANGELOG.md, pkg/client/linstor.go
In case creating a new volume takes longer than the GRPC timeout,
the provisioner could get in a state where volumes are considered
ready even if no resource was ever created. This commit fixes this
issue by ensuring that volumes are only considered ready after the
expected amount of volumes was placed.
The bug happened in cases where:
* `Create()` succesfully called `saveVolume()`, persisting the volume
information as annotations, which is interpreted as "ready" resources
* Immediatly after, the GRPC timeout cancels the request context, meaning
the volume scheduler aborted before any resources could be assigned to
nodes
A simple reording of `volumeScheduler.Create()` and `saveVolume()` would
lead to a different issue, in which continuously more volumes are placed
but never marked as …
=> Fix a idempotency issues in CreateVolume

CHANGELOG.md, pkg/topology/scheduler/balancer/balancer.go, pkg/volume/volume.go
The LayerList must be passed to LINSTOR anytime a resource is created.
This commit adds the information to all create calls. Previously, it was
only done in AutoPlace requests.
Fixes #102
=> pass layerlist in all resource create requests

CHANGELOG.md, README.md, go.mod, go.sum, pkg/client/linstor.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/volume/volume.go, test/compat_test.go
The changes in detail:
Instead of storing snapshot information in resource definitions, use native
LINSTOR snapshots. This makes it easier to retry a timed out snapshot attempt.
A basic test was added using "old" format LINSTOR responses to ensure no
information is lost in transition.
To ensure stable snapshot ID between tries, the suggested name is either
used directly or a generated UUIDv5 based on the name is used. Since the CSI
snapshotter image will always suggest a compatible name, this is mostly done
for complying with the CSI spec.
In volume-from-volume scenario, re-use the snap-create and vol-from-snap logic
instead of implementing it in the LINSTOR client. This is done by first creating
a stable snapshot name for the new PVC, restoring using the existing
vol-from-snap logic and …
=> Snapshot refactor

CHANGELOG.md, pkg/driver/driver.go
Restored snapshots inherit the XFS UUID of the original source. If mounted
on the same node as the original without the "nouuid" option, XFS will
complain about a duplicate UUID and refuse to mount.
=> add "nouuid" option to XFS mounts

CHANGELOG.md, pkg/client/linstor.go, pkg/driver/driver.go, pkg/volume/volume.go, pkg/volume/volume_test.go
This commit enables deletion of PV while taken snapshots are kept around.
To implement this a couple of changes needed to be made:
Snapshots in LINSTOR are attached to a ResourceDefinition (RD), not to the
Resources directly. This means we can remove a PV by deleting the Resources
in LINSTOR without deleting the RD.
In turn, we cannot rely on the "volume.Info" struct to exist when
restoring from a snapshot. While it was queried, it actually did not serve
any purpose, the query is just removed.
Not deleting the RD on PV deletion requires another set of changes:
* Once the last RD "user" (Resource or Snapshot) is deleted, we need to
delete the RD (and maybe also the Resource Group)
* We use aux props on the RD to persist important metadata. Specifically,
it was also used to identify RDs and …
=> Make snapshots independent from their source PV

pkg/client/linstor.go
Diskless resources need to be deleted before all diskfull resources are gone.
Otherwise the last diskfull resources can't ever be deleted. The easiest
way to ensure that diskfull resources are deleted last is by sorting the
resources beforehand.
Bug was introduced in #107.
=> fix deletion order of diskless resources

CHANGELOG.md, pkg/client/linstor.go, pkg/linstor/const.go
We want to delete resources that were only created to facilitate an Attach()
request. The way this was determined was by checking if the given resource is
diskless or not. This presents a problem, as there are a number of ways
diskless resources get created:
* Linstor creates a TieBreaker resource
* The user specified that a Diskless resource should be placed on that node
* Attach() was called for a node were the resource was not present
From the point of view of Detach(), all these above cases look the same, and
so the resources were deleted even if they did not originate from the Attach.
This commit adds a new property to resources generated by Attach. This way
Detach can later check for the presence of this property, and only delete
the resource if:
* The resource has the "Attach" …
=> only delete resources on Detach if created in Attach

CHANGELOG.md, pkg/client/linstor.go
Operations that should reconcile the creation of resource did not check
for the DELETE flag if a resource with matching ID was already created. This
meant that later stages potentially tried using resources that no longer exist.
=> Fix handling of DELETE flag on resource creation

pkg/client/linstor.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/volume/volume.go, test/compat_test.go
In some cases snapshots are created but fail to become "successful",
for example when one of the satellite goes offline at the wrong moment.
In such cases, we want to delete the failed attempt, as otherwise
the CSI snapshotter will forever wait for the snapshot to get ready.
This then produces a lot (read: gigabytes) of logs, as it tries polling
the snapshot state again multiple times per second.
This commit adds logic to recognize such failed snapshots and remove+retry
them. Note that currently there is no way to tell the snapshot controller that
a snapshot can't ever succeed, for example when a storage driver without
snapshot support is used.
=> Remove failed attempts at creating a snapshot

go.mod, go.sum
A bug in previous golinstor versions meant that responses that
included Volume information always created errors. The broken
golinstor version was only included in 8653ba34f
=> Bump golinstor to v0.34.3

CHANGELOG.md, cmd/linstor-csi/linstor-csi.go
If the LINSTOR HTTP API is secured by a project like kube-rbac-proxy, which
secures an endpoint by delegating authentication to the kubernetes built-ins,
namely serviceaccounts and RBAC rules, we need a way to send our
authentication in the form of a bearer token.
On start-up, the token is read from a file specified on the command line. The
Header is added in a specialized http.RoundTripper implementation, since
golinstor currently does not support setting default headers.
This implementation even has the benefit of not logging the token on every
request.
Signed-off-by: Moritz "WanzenBug" Wanzenböck <moritz.wanzenboeck@linbit.com>
=> Add bearer authentication for HTTP API

go.mod, go.sum, pkg/topology/scheduler/followtopology/follow_topology.go, pkg/topology/scheduler/followtopology/follow_topology_test.go
The CSI spec requires very specific behaviour when using
AccessibilityRequirements/Topology.
A CreateVolumeRequest contains:
* A list of requisite topologies. The volume _has_ to be accessible
from at least on of these. If the list is empty, any placement is allowed.
* A list of preferred topologies. If a list of requisites is also given,
preferred is a subset of the requisite topologies. They should be considered
first when placing volumes, but there is no requirement that a volume
has to be accessible from a preferred topology.
This commit adds support for requisite and/or preferred topologies when using
the "FollowTopology" policy.
=> Make "FollowTopology" adhere strictly to CSI spec

CHANGELOG.md, README.md, examples/k8s/class.yaml, pkg/client/linstor.go, pkg/client/linstor_test.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/linstor/const.go, pkg/topology/topology.go, pkg/volume/volume.go, pkg/volume/volume_test.go
While the `GetCapacity()` call was already implemented, it was not usable in practice:
1. The parameters from the storage class are passed 1:1 to the GetCapacity request. This is an issue when some "external" parameters are present in the storage class. The most obvious example of such a parameter is `csi.storage.k8s.io/fstype`, which we even include in our examples.
When creating volumes, `csi.storage.k8s.io/fstype` seems to be removed from the request passed to the plugin by the provisioner, but for `GetCapacity`, the parameters seem the remain unchanged. Why that difference exists, I cannot say.
In any case, to work around this, we ignore parameters with a foreign "namespace" section. For consistency, our own parameters can now also be namespaced using `linstor.csi.linbit.com`. …
=> Add support for CSI Storage Capacity queries

CHANGELOG.md, go.mod, go.sum, pkg/client/linstor.go, pkg/topology/placementpolicy_enumer.go, pkg/topology/scheduler/autoplace/autoplace.go, pkg/topology/scheduler/autoplacetopology/autoplacetopology.go, pkg/topology/scheduler/autoplacetopology/autoplacetopology_test.go, pkg/topology/scheduler/followtopology/follow_topology.go, pkg/topology/topology.go, pkg/volume/volume.go
This new scheduler is a topology aware version of the old `AutoPlace`
scheduler. Since it is topology aware, it can be used to optimize volume
placement when using `WaitForFirstConsumer` volume binding or restricting
placement via `allowedTopologies`, while still respecting user-defined
placement options such as `replicasOnSame` or `replicasOnDifferent`.
This scheduler was added as all alternatives have some issue:
* `AutoPlace` completely ignored topology information, making it a bad fit for optimized volume placement based on Pod scheduling.
* `FollowTopology` ignored user set constraints  like `replicasOnSame` and `replicasOnDifferent`
=> Add new default "AutoPlaceTopology" scheduler

pkg/client/linstor.go, pkg/topology/scheduler/autoplacetopology/autoplacetopology.go
In https://github.com/piraeusdatastore/piraeus-operator/commit/530c7aed27ea9640516d40b5095a6eb1248285fe the operator learned to sync node labels to LINSTOR properties. To make CSI (and kubernetes) aware that the linstor plugin is capable of scheduling based on these labels, we need to add them in the node info response.
The change requires some changes in the volume scheduler: now it is possible for a user to specify a general topology, which might not contain the previously assumed single-node identification. Instead of assuming that a segment contains exactly one node, the scheduler now deals with multiple nodes per segment by fetching matching nodes from LINSTOR.
=> node: add aux properties as additional topology info

CHANGELOG.md, pkg/topology/scheduler/followtopology/follow_topology.go
The change to use the make-available API in the FollowTopology scheduler
introduced in b4daec3dca3ec3174e084fc744dd5d11c17ceb63 worked under
the assumption that make-available would deploy diskful resources
unless explicitly told to use diskless resources.
This assumption is the exact opposite of the actual behaviour. That meant
that all new FollowTopology resources were effectively only using 1 replica.
This commit explictily requests diskful resources during initial deployment,
fixing the above issue.
Signed-off-by: Moritz "WanzenBug" Wanzenböck <moritz.wanzenboeck@linbit.com>
=> Fix make-available to ensure diskful deployment

pkg/client/linstor.go
golinstor returns nil for the creation timestamp of snapshots in case
linstor does not provide one. This caused an NPE when converting it to
a CSI snapshot object.
=> fix a NPE during snapshot operations

CHANGELOG.md, pkg/client/linstor.go, pkg/driver/driver.go, pkg/linstor/const.go, pkg/volume/volume.go
73c97a8 reworked the normal order of API calls when creating new volumes.
Instead of the traditional RD -> VD -> AP, it used RD -> AP -> VD. This
was done because we need a way to distinguish in-progress create requests from
those where the volume already exsists. Creating the VD in the last step made
it easy to check. Before 73c97a8, this was done by a specific aux property,
that was also used to pass volume parameters to later calls.
Creating the VD last proves to be problematic:
* On "thick" storage, it will generate inconsistent DRBD devices, as LINSTOR
doesn't do it's forced primary trick for "late" volume additions.
* On "thin" storage, it will sometimes trigger a race condition, confusing
LINSTOR into simultaneously not creating the volume and not deleting it.
This commit addresses …
=> Revert to using normal volume create order

CHANGELOG.md, cmd/linstor-csi/linstor-csi.go, examples/k8s/class.yaml, go.mod, pkg/client/linstor.go, pkg/driver/driver.go, pkg/linstor/highlevelclient/high_level_client.go, pkg/topology/scheduler/autoplace/autoplace.go, pkg/topology/scheduler/autoplacetopology/autoplacetopology.go, pkg/topology/scheduler/autoplacetopology/autoplacetopology_test.go, pkg/topology/scheduler/balancer/balancer.go, pkg/topology/scheduler/followtopology/follow_topology.go, pkg/topology/scheduler/manual/manual.go, pkg/topology/scheduler/scheduler.go, pkg/volume/parameter.go, pkg/volume/remoteaccess.go, pkg/volume/remoteaccess_test.go
Up to now, using diskless volumes was an all-or-nothing affair: either allow
diskless resource from any node, or don't allow them at all. This was quite
limiting for more advanced cluster architectures.
For example, clusters spanning multiple zones could not restrict diskless
access to only nodes in the same zone. Similarly, if you had dedicated storage
hosts, you could not restrict diskless volumes to a specific subset.
Another issues was in the calculation of storage capacity. In case of dedicated
storage hosts, the storage capacity was effectively 0 on almost all nodes,
meaning pods were never scheduled on those nodes, even tough diskless access
from the dedicated storage was possible.
As a solution, introduce new values for the `allowRemoteVolumeAccess`
parameter. It now takes a list …
=> Advanced volume access rules

CHANGELOG.md, pkg/client/linstor.go, pkg/client/linstor_test.go
replicasOn... parameters are intended for spreading the intial set of replicas.
For volume use, it might be required to attach the volume to a node that would
violate the requirements. As a high level argument, you could say that these
temporary attached volumes are not really replicas in the sense implied by
replicasOn... parameters.
The fix is to fall back to manual resource creation if required. Note that we
do not always use this manual creation, as in some cases it is advantageous
to try make-available first. For example, in a shared storage pool scenario
make-available will pick a new shared resource over diskless attachment.
Signed-off-by: Moritz "WanzenBug" Wanzenböck <moritz.wanzenboeck@linbit.com>
=> attach: ignore replicasOn... parameters if required

CHANGELOG.md, pkg/client/linstor.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/volume/parameter.go, pkg/volume/paramkey_enumer.go, pkg/volume/volume.go
A new parameter `usePvcName` is added. When "true", the driver will (try to)
use the PVC name + namespace instead of the generated PV name as ID. Because
this might generate name conflicts in certain scenarios, it remains disabled
by default.
=> New "usePvcName" parameter for user-controlled names

CHANGELOG.md, pkg/client/linstor.go, pkg/driver/driver.go
If a node is deleted from k8s and LINSTOR, the volume attachments might
still hang around, triggering ControllerUnpublishVolume calls on nodes
that no long exist.
This commit ensures we handle this case gracefully, detaching from the "lost"
node. Since the node was already deleted from LINSTOR, there isn't actually
anything for us to-do on detach.
=> unpublish: ignore errors generated by deleted nodes

.github/workflows/release.yml
In some circumstances it might be preferable to run LINSTOR CSI as
a binary instead of in a container. As an example, Nomad can use CSI drivers
without having a container runtime installed.
=> upload binary as release asset

CHANGELOG.md, pkg/client/linstor.go
Newer LINSTOR releases prevent expansion of volumes that are not in sync.
This prevents bugs when resizing DRBD devices while sync is in progress.
The CSI driver expands volume in two cases:
1. When the user requests an existing volume to be resized.
In this case we can expect the resource to be in sync already, so there
is no special consideration. In the worst case, the operation is simply
retried a bit later.
2. When a snapshot is restored, or a volume cloned.
In this case, right after we complete the restore operation, the volumes
are likely still syncing. This is because we only clone the data from a
single node and letting DRBD do the replication itself. This was introduced
in cd699d661 in order to support changing parameters on restored volumes,
and is also used for restoring from …
=> expand restored volume before deploying to multiple nodes

.pre-commit-config.yaml, CHANGELOG.md, pkg/client/linstor.go, pkg/client/linstor_test.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/driver/volume_context.go, pkg/volume/parameter.go, pkg/volume/volume.go
Replaces custom mkfs formatting code with LINSTOR built-ins. This replaces
the formatAndMount check at node attach time with simply setting properties
on the ResourceDefinition.
Note that we do not set it on the ResourceGroup (~ StorageClass) level, as
filesystem is determined by the PersistentVolumeClaim (~ ResourceDefinition)
being created.
Signed-off-by: Moritz "WanzenBug" Wanzenböck <moritz.wanzenboeck@linbit.com>
=> delegate mkfs to LINSTOR

Dockerfile
Docker image `debian:bullseye-slim` does not contain `/etc/mtab` symlink. While docker is setting it [automatically](https://github.com/moby/moby/blob/master/daemon/initlayer/setup_unix.go#L25-L36) for every container, containerd is not doing this.
This affects Kubernetes deployments with containerd, which are report the following warning every time when attaching a new volume to pod:
```
mke2fs 1.44.5 (15-Dec-2018)
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/drbd1000 is mounted.
```
This confuses the end users of linstor-csi plugin.
=> Fix mtab warning for mkfs commands

CHANGELOG.md, pkg/client/linstor.go, pkg/client/linstor_test.go
When restoring a snapshot from S3 backup, LINSTOR CSI will have to select
a node on which to download the backup. This should have always been the
preferred node (which was likely chosen by the workload scheduler). However,
we only considered the requisite topology, which is not always good enough.
With this commit we sort the requisite nodes by their preference, so in the
ideal case, the snapshot is downloaded directly on the node that will consume
the new volume.
=> order snapshot restore based on preferred nodes

CHANGELOG.md, pkg/client/linstor.go, pkg/driver/driver.go, pkg/driver/volume_context.go, pkg/linstor/const.go
This PR is focused on improving support for external components that need to interact with LINSTOR CSI resources:
* Export the CSI driver name. This was a tiny papercut, but having to specify the full driver name every time sucked.
* Export the remote access policy parameter. This value is important for some external components such as LINSTOR Scheduler and LINSTOR Affinity Controller. Having to parse the storage class just for that is pretty error-prone, as there is no guarantee that the storage class still exists or that is the same storage class used during provisioning.
=> support for external components

CHANGELOG.md, cmd/linstor-csi/linstor-csi.go, pkg/client/linstor.go, pkg/client/linstor_test.go, pkg/linstor/highlevelclient/high_level_client.go
Adds options to:
* Change the default mapping of linstor node properties to k8s node labels
* Disable the node labels generated for storage pools.
This is done to create a more consistent user experience in a new operator release:
* The default mapping of all auxiliary properties caused some implementation details to leak (for example: all nodes suddenly had a `registered-by: piraeus-operator` label
* The storage pools were mostly unused, but required some extra code to keep in sync, such as restarting the CSI pod on any addition/removal.
=> Add option to configure which topology keys are exported

pkg/client/linstor.go, pkg/client/linstor_test.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/linstor/const.go, pkg/volume/volume.go
This PR allows to live-migrate KubeVirt virtual machines by setting `allow-two-primaries` flag dynamically.
fixes https://github.com/piraeusdatastore/linstor-csi/issues/159
* **controllerPublishVolume:**
* if volume has `type: Block` and `accessMode: ReadWriteMany`;
* if it is already `InUse` at one other node;
enables `allow-two-primaries` flag
* **controllerUnpublishVolume:**
* if volume `InUse` at one one less amount of nodes
removes `allow-two-primaries` flag
=> Support live-migration with allow-two-primaries

CHANGELOG.md, pkg/client/linstor.go
LINSTOR API should filter for the snapshot name already, but does not always seem to do so in all cases. Since we iterate and filter some results already, we can also check that the original snapshot name matches the expected ID.
=> backups: filter all backups based on ID

CHANGELOG.md, pkg/driver/driver.go
This ensures unmounting happens before the network stack is torn down during node shutdown, preventing situations where DRBD would lose quorum before systemd had the chance to unmount all CSI controlled mounts.
=> Add _netdev option to all mounts

CHANGELOG.md, pkg/client/linstor.go
When scheduling Pods, the default kubernetes scheduler takes into account the reported storage capacity of nodes. Up to now, we also reported the capacity of evicted/evacuated or "AutoplaceTarget=false" nodes. This meant that Kubernetes tried to schedule Pods on nodes where storage could never be attached.
The (partial) fix is to ignore nodes during storage capacity accounting. This means users with stricter topology requirements get a reported capacity of 0 for those nodes.
It is not a complete fix, as from the CSI side we don't have a way mark the node as completely unscheduable.
=> ignore unschedulable nodes in capacity requests

CHANGELOG.md, cmd/linstor-csi/linstor-csi.go, pkg/client/linstor.go, pkg/driver/driver.go, pkg/topology/scheduler/autoplacetopology/autoplacetopology.go, pkg/volume/parameter.go, pkg/volume/remoteaccess.go, pkg/volume/volume.go, pkg/volume/volume_test.go
Since 0.21.0, users where able to change the default "namespace" where the CSI driver would expect topology information to be available on the node.
Until now, we did not change the prefix functionallity for settings replicas-on-same/different in the parameters: they were always prefixed with Aux/.
This became a problem with Operator v2, which configures Aux/topology as the default namespace for these kinds of labels. To fix, we change the prefix function to include the support the property namespace.
All "absolute" property names (i.e. those already prefixed with Aux/) are left untouched, so people can still refer to properties outside the namespace if they wish to do so.
=> Use property namespace to prefix replica-on-* conf

CHANGELOG.md, pkg/client/linstor.go, pkg/client/linstor_test.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/volume/volume.go
The CSI driver had a special case for attaching volumes to a degraded cluster. This is no longer necessary, as DRBD now (9.1.12/9.2.0) calculates quorum differently, meaning adding diskless to a degraded cluster still works.
=> remove quorum workaround

CHANGELOG.md, pkg/client/linstor.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/volume/volume.go, test/compat_test.go
Implement deletion for S3 snapshots/backups by calling the appropriate API in the DeleteSnapshot() call.
In order to speed up this process, we also enhance the existing Find/ListSnapshot functions to return the originating LINSTOR remote name. This both identifies the item as a backup, and helps with the delete calls.
=> implement deletion for backups

CHANGELOG.md, examples/k8s/volume-snapshot-class.yaml, pkg/driver/driver.go, pkg/volume/snapshot_params.go
When creating a remote backup in LINSTOR, we can remove the local snapshot after shipping completes.
=> implement deletion of local snapshots for S3 backups

CHANGELOG.md, pkg/client/linstor.go
This is normally enforced by the provisioner, but when restoring from a backup without reported snapshot size, the provisioner cannot enforce this limit.
Instead we simply update the check to ensure the volume definition is never shrunk.
=> Prevent shrinking of volumes

CHANGELOG.md, cmd/linstor-csi/linstor-csi.go, pkg/client/linstor.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/volume/volume.go
When a user requests a restore from an off-site backup, they might want the local snapshot to be deleted after the restore.
We already have this option when creating the snapshot by using a special parameter on the snapshot class. However, we do not have that information available directly.
To support this, we need to lookup the snapshot content and snapshot class ourselfes, then parse the parameters. This is all optional, as LINSTOR CSI still needs to work outside kubernetes, or inside Kubernetes with incomplete information.
=> support deletion of snapshots after restore from backup

CHANGELOG.md, pkg/client/linstor.go, pkg/client/linstor_test.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/linstor/highlevelclient/high_level_client.go, pkg/volume/parameter.go, pkg/volume/paramkey_enumer.go, pkg/volume/volume.go
Adds a new overprovision parameter that calculates the capacity of a given
storage pool based on the existing reserved space.
While we would like to use LINSTOR directly for that, it does not seem to
be implemented: the "query-size-info" call seems to return inconsistent
results.
The advantage of the new parameter is that people can opt-in to this new
calculation by setting the parameter.
This also adds a cache for the call to `Resources.GetResourceView()`, as the CapacityBytes() is one of the "hottest" code paths, and we don't actually need to monitor the usage that closely.
=> Add over provision factor

CHANGELOG.md, pkg/client/linstor.go, pkg/client/linstor_test.go
When chosing a node to download our backup, we should prevent the same node from downloading the backups all the time.
In the case we get a "preferred" topology, this is left to the kubernetes scheduler/CSI controllers: they should select different preferred nodes.
In the case we have no preferred topology given to use, we should do our own random selection. Otherwise we end up with the same node being chosen to download backups all the time, while the others sit idle.
=> backups: select random node to download backup

CHANGELOG.md, go.mod, go.sum, pkg/client/linstor.go, pkg/volume/parameter.go
Fixes some issues in the AttachVolume call and beyond:
* Do not try to attach a resources that does not have a replica
* Do not try to create a diskless resource if the resource does not support it
* Set default access policy to "local only" for resources without replication layer
=> Fixes around attaching volumes with unusual resources

CHANGELOG.md, pkg/client/linstor.go, pkg/client/linstor_test.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/topology/scheduler/balancer/balancer.go, pkg/volume/parameter.go, pkg/volume/volume.go, pkg/volume/volume_test.go
LINSTOR Resource Groups can have multiple storage pools set in a single resource group. LINSTOR then selects one matching pool for every resource placement.
Since storage pool names cannot contain any spaces, there should be no existing storage class with spaces in the storage pool parameter. This means we can simply reuse the existing parameter.
=> params: allow setting multiple storage pools

Dockerfile
Some tools that interact with the kernel are not happy when using old tools on a new kernel. For example, turns out that resize2fs (the ext* resize tool) refuses to resize a mounted FS on a new kernel because the FS there reports some features it does not know about.
To fix, we use the latest debian stable release as our base image. Tools there should be new enough for the future.
See https://github.com/piraeusdatastore/piraeus-operator/issues/628
=> docker: switch base to debian 12

pkg/client/linstor.go
We delete the volume definition in order to have resource definitions without resources. This is useful when we want to keep snapshots without having the associated resources around.
During the volume deletion, we first delete the volume definition. This may be causing a bug in DRBD 9.2, so we delay the deletion until after all resources are gone, at which point DRBD has fully shut down the resource.
=> delay deletion of volume definitions

CHANGELOG.md, go.mod, go.sum, pkg/client/linstor.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/linstor/const.go, pkg/volume/snapshot_params.go, pkg/volume/volume.go
Fill in the missing implementation for backup shipping to another LINSTOR cluster. Because we can't "wish" for a specific snapshot name, we store a mapping of requested snapshot name to actually taken snapshot name in a special LINSTOR KV.
Other than that, it is simply a matter of wiring up the necessary plumbing.
This currently cannot restore a backup once it is shipped and the local snapshot deleted, and it is unlikely that such a thing could be implemented, as LINSTOR does not support downloading a snapshot once shipped.
=> implement L2L backup shipping

Dockerfile, cmd/linstor-csi/linstor-csi.go, go.mod, go.sum, pkg/client/linstor.go, pkg/driver/driver.go, pkg/driver/volume_context.go
* Upgrading golinstor to improve cache invalidation when creating/restoring backups
* Fix two-primaries special case resulting in unexpected errors
* Sanity check the we actually forward a device name to the csi-node component
* Reduce resouce cache timeout to below default provisioning time to reduce wait time for provisioning
=> Various fixes + improvements with respect to recent caching changes

CHANGELOG.md, go.mod, go.sum
The golinstor caching implementation did not filter by properties, which is used by the NodesForTopology() call to filter the nodes based on properties.
This meant that in some scenarios, LINSTOR CSI would place volumes on unexpected nodes, as it got the full list of nodes instead of one filtered to just some property.
=> update golinstor to fix caching issue

CHANGELOG.md, pkg/client/linstor.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/volume/volume.go
Block volumes cannot be resized, so there is no point in even attempting it. An attempt would fail because it could not determine the FS one the volume, as there likely isn't any. A retry would then succeed as there is an earlier check if we need to mount at all.
The fix is to rearrange the logic to only attempt to resize filesystem volumes.
While at it, also remove the deprecated "IsNotMountPoint". The double negative was getting confusing in any case.
=> do not try to resize block volumes

CHANGELOG.md, pkg/client/linstor.go
A node may be offline. Since we select only one node, we should ensure it is not offline.
=> snapshot: do not restore on offline nodes

CHANGELOG.md, pkg/client/linstor.go
If a user requests a RW volume, we disable the default behaviour of "mount" to fallback to RO mounts should there be an issue with the initial RW attempt.
This may happen if a DRBD device is in a weird state, where the default auto-promote does not succeed, but the resource is otherwise fine. A RO mount does not require an explicit state change, so it may succeed in such a situation.
By requesting "rw" in the mount options, we prevent this behaviour.
=> disable fallback to RO mounts for RW volumes

pkg/client/linstor.go
Passing the "rw" option is not enough. Careful reading of the manpage, verified by tests and reading of the source code of util-linux reveals that disabling the RO fallback only happens when you pass the "-w" flag.
Then, also fix "ro" mounts in case of XFS, as XFS attempts to write even if passed the "ro" flag without the "norecovery" option.
Fixes: 6deb565 ("disable fallback to RO mounts for RW volumes")
=> really disable fallback mounting to RO

CHANGELOG.md, pkg/driver/driver.go
Up to now, we did not properly validate volume capabilities during volume creation, allowing users to create FileSystem volumes with RWX capabilities.
Careful reading of the CSI standard shows that these capabilities need to be checked during CreateVolume and ValidateVolumeCapabilities calls.
=> better volume validation

CHANGELOG.md, go.mod, go.sum, pkg/client/linstor.go
* golinstor used to invalidate the cache before applying modifications. This might cause stale cache entries if the cache gets re-populated before the modification is made. The end result was that sometimes the CSI driver thought that certain resource should not be deleted. An update to golinstor fixes this issue.
* LINSTOR periodically runs a job that recreates replicas based on the RG settings. This sometimes interfered with our deletion logic, causing resource to not be properly cleaned up, leaving resources with no volumes and the resource definition behind. To fix this, disable the task for the resources we intent to delete.
=> fix issues with left-over resource definition after volumes have been deleted

CHANGELOG.md, go.mod, go.sum, pkg/client/linstor.go, pkg/client/mock.go, pkg/driver/driver.go, pkg/volume/volume.go
We already supported cloning volumes via snapshots. Since LINSTOR now can also clone volumes, and be smart about mixing and matching different storage pools, we can switch to using the LINSTOR clone path, enabling clones on more types of storage pools.
=> supported LINSTOR volume clones

CHANGELOG.md, pkg/client/linstor.go
We want to ensure a mapped block volume are usable. Since we only bind-mount the device to a new location, we never verify that the device is usable. This may lead to a device that has no quorum being used. Depending on the workload using that device, this may go unnoticed.
So we do a simple sanity check by opening the device. A "rw" device opening fails immediately on open, a "ro" device might only fail on reading a specific sector. Since we can't really read the whole device, no additional checks are added for this case.
=> sanity check that block volumes are usable

pkg/driver/driver.go
This pull request updates the `CreateVolume` function in the LINSTOR CSI driver to always extract and utilize the PVC name and namespace from the CSI request parameters. These values are now used to generate a more consistent volume ID and are optionally added to the volume's properties in LINSTOR for improved metadata tracking and debugging.
Motivation
- By always attempting to use these parameters (with safe fallbacks), we ensure better alignment with Kubernetes PVC metadata.
- Storing PVC details in LINSTOR properties (e.g., as `Aux/csi.storage.k8s.io/pvc/name` and `Aux/csi.storage.k8s.io/pvc/namespace`) allows for easier querying and association of volumes with their originating PVCs via LINSTOR commands or API, without relying on external tools.
This change is backward-compatible in …
=> Always use PVC name and namespace in volume creation and store as Aux properties
